import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Cristian',
      email: 'Cristian@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Angel',
      email: 'Angel@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'Eduardo',
      email: 'Eduardo@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Hamburguesa',
      slug: 'hamburguesa',
      category: 'Hambuguesas',
      image: '/images/hamburgesa.jpg',
      price: 3000,
      brand: 'McDonalds',
      rating: 4.5,
      numReviews: 10,
      countInStock: 200,
      description: 'Hamburguesa de carne, con queso, lechuga, tomate, pepinillos y cebolla',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Papas fritas',
      slug: 'papas fritas',
      category: 'Acompañamientos',
      image: '/images/papafrita.jpg',
      price: 1500,
      brand: 'McDonalds',
      rating: 4.0,
      numReviews: 10,
      countInStock: 300,
      description: 'Papas fritas con sal',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Coca Cola',
      slug: 'coca cola',
      category: 'Bebidas',
      image: '/images/coca.png',
      price: 1200,
      brand: 'Coca Cola',
      rating: 4.5,
      numReviews: 100,
      countInStock: 1000,
      description: 'Coca Cola 500ml, sabores: normal, light, zero',
    },
    {
      name: 'Sprite',
      slug: 'sprite',
      category: 'Bebidas',
      image: '/images/Sprite.jpg',
      price: 1000,
      brand: 'Sprite',
      rating: 4.3,
      numReviews: 500,
      countInStock: 500,
      description: 'Sprite 500ml, sabores: normal, light, zero',
    },
    {
      name: 'Fanta',
      slug: 'fanta',
      category: 'Bebidas',
      image: '/images/fanta.png',
      price: 1000,
      brand: 'Fanta',
      rating: 4.4,
      numReviews: 500,
      countInStock: 500,
      description: 'Fanta 500ml, sabores: normal, light, zero',
    },
    {
      name: 'Empanadas de queso',
      slug: 'empanadas de queso',
      category: 'Acompañamientos',
      image: '/images/empquezo.jpg',
      price: 2000,
      brand: 'McDonalds',
      rating: 5.0,
      numReviews: 1200,
      countInStock: 1000,
      description: '8 Exquisitas empanadas de queso',
    },
    {
      name: 'WD-40',
      slug: 'wd-40',
      category: 'Acompañamientos',
      image: '/images/wd40.jpg',
      price: 500,
      brand: 'Made in China',
      rating: 1.0,
      numReviews: 5000,
      countInStock: 200,
      description: 'WD-40 227g',
    },
  ],
};

export default data;
